---
abstract: 'An extension of Async::Blackboard which uses AnyEvent'
author:
  - unknown
build_requires:
  BSD::Resource: 0
  Devel::Leak: 0
  EV: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Blackboard
provides:
  AnyEvent::Blackboard:
    file: lib/AnyEvent/Blackboard.pm
    version: v0.4.8
requires:
  AnyEvent: 0
  Async::Blackboard: v0.3.10
  Mouse: 0
version: v0.4.8
