---
abstract: 'A simple blackboard database and dispatcher.'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Blackboard
provides:
  AnyEvent::Blackboard:
    file: lib/AnyEvent/Blackboard.pm
    version: v0.2.3
requires:
  AnyEvent: 0
  Mouse: 0
version: v0.2.3
